---
#create_containers: 1
default_container_name: nginx_test
default_container_image: nginx:latest
#default_container_command: sleep 1d
docker_username: Pass_docker_username
docker_password: Pass_docker_password
image: swapnillinux/apache-php
name: myweb
src_port: 8080
dest_port: 80
src_vol: /mnt/www
dest_vol: /var/www/html
privileged: true
